services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.3
    ports:
    - "8123:8123"
    environment:
      CLICKHOUSE_USER: "user"
      CLICKHOUSE_PASSWORD: "password"
      CLICKHOUSE_DB: "ldv_logging"
